server:
    port: 8080

spring:
    datasource:
        url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
        name: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true

logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: trace
